#!/usr/bin/env bash

#export LANG=C

__vvis_exec=$(mktemp)
cat << 'EOF' > ${__vvis_exec}
#!/usr/bin/env bash
TERM="" exec vis "+set autoindent" \
	"${@}"
EOF
chmod +x "${__vvis_exec}"
function vxis {
	"${__vvis_exec}" "${@}" ;}

__vvimrc=$(mktemp)
cat << 'EOF' > ${__vvimrc}
set shortmess=I
set nowrap
set softtabstop=0 noexpandtab
set tabstop=8
set shiftwidth=8
set linebreak
set autoindent
set hlsearch
set term=builtin_ansi
noremap * *N
command -range Y '<,'>w! ~/__
command P r ~/__
colorscheme industry
syntax on
noh
EOF
chmod +r "${__vvimrc}"

__vvim_exec=$(mktemp)
cat << EOF > ${__vvim_exec}
#!/usr/bin/env bash
TERM="\$TERM" vim -S "${__vvimrc}" "\${@}"
EOF
chmod +x "${__vvim_exec}"
function vvim {
	"${__vvim_exec}" "${@}" ;}
EDITOR="${__vvim_exec}"

#__screen_config=$(mktemp)
#cat << 'EOF' > ${__screen_config}
#layout save default
#EOF
#function sscreen {
#	screen -c "$__screen_config" "${@}" ;}

__bbash_exec=$(mktemp)
cat << 'EOF' > ${__bbash_exec}
#!/usr/bin/env bash
exec bash --init-file <(echo ". ~/.bashrc; . ~/.baxsh;") "${@}"
EOF
chmod +x "${__bbash_exec}"
function bbash {
	"${__bbash_exec}" "${@}" ;}

__dxvtm_exec=$(mktemp)
cat << EOF > ${__dxvtm_exec}
#!/usr/bin/env bash
DVTM_EDITOR="${__vvim_exec}" SHELL="${__bbash_exec}" DVTM_TERM="$TERM" exec dvtm -m '^ ' -s <(exit) "${@}"
EOF
chmod +x "${__dxvtm_exec}"
function dxvtm {
	"${__dxvtm_exec}" "${@}" ;}

function aabduco {
	ABDUCO_CMD="${__dxvtm_exec}" abduco \
		"${@}" ;}

export EDITOR="${__vvim_exec}"

#. ~/.nvm/nvm.sh --no-use
[ -f ~/.nvm/nvm.sh ] && . ~/.nvm/nvm.sh
